### ISSUE TITLE
Extend sync-options annotation with `Force=true` 

### ISSUE THREAD

**Issue by n9** [argoproj/gitops-engine#525] opened 2023-05-30 08:03 UTC
Solution for https://github.com/argoproj/argo-cd/issues/5882

Use case: e.g. to replace certain pod

(I will try to implement it.)

**Comment by morey-tech** [comment] 2023-06-02 16:25
This issue might be a duplicate of https://github.com/argoproj/gitops-engine/issues/414, you could close this and link your PR to the older one

**Closed** 2023-06-02 18:46 UTC
